name: MealMatch
description: An interactive social platform to combat food insecurity and improve communities

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+2

environment:
  # https://stackoverflow.com/questions/64621051/how-to-enable-null-safety-in-flutter
  sdk: ">=2.12.0-0 <3.0.0"
  #sdk: ">=2.7.0 <3.0.0"

#https://github.com/danvick/flutter_form_builder/issues/676
dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: any
  provider: any
  flutter_spinkit: any
  gradient_text: any
  dots_indicator: any
  firebase_core: any
  firebase_analytics: any
  firebase_auth: any
  firebase_storage: any
  cloud_firestore: any
  flutter_form_builder: any

  # this is a workaround for a recent bug
  # https://github.com/danvick/flutter_form_builder/issues/674
  flutter_typeahead: "<=1.9.1"

  url_launcher: any
  google_fonts: any
  dash_chat: any
  shared_preferences: any
  curved_navigation_bar: any
  flutter_google_places: any
  google_maps_webservice: any
  uuid: any
  geodesy: any
  camera: any
  path_provider: any
  path: any
  flutter_launcher_icons: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: any

  geolocator: any
  geocoding: any
  firebase_messaging: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_android: "./assets/mealmatchicon.png"
  image_path_ios: "./assets/mealmatchicon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/logo.png
    - assets/intro-1.png
    - assets/intro-2.png
    - assets/intro-3.png
    - assets/mealmatchicon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
