name: MealMatch
description: An interactive social platform to combat food insecurity and improve communities

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: '>=2.2.1'
  provider: '>=4.1.3'
  flutter_spinkit: '>=4.1.2'
  gradient_text: '>=1.0.2'
  dots_indicator: '>=1.0.0'
  firebase_core: '>=0.5.3'
  firebase_analytics: '>=6.3.0'
  firebase_auth: '>=0.18.4+1'
  firebase_storage: '>=5.2.0'
  cloud_firestore: '>=0.14.4'
  flutter_form_builder: '>=4.2.0'

  # this is a workaround for a recent bug
  # https://github.com/danvick/flutter_form_builder/issues/674
  flutter_typeahead: "<=1.9.1"

  url_launcher: '>=5.5.0'
  google_fonts: '>=1.1.0'
  dash_chat: '>=1.1.14'
  shared_preferences: '>=0.5.10'
  curved_navigation_bar: '>=0.3.3'
  flutter_google_places: '>=0.2.6'
  google_maps_webservice: '>=0.0.18'
  uuid: '>=2.2.2'
  geodesy: '>=0.3.2'
  camera: '>=0.5.8+11'
  path_provider: '>=1.6.24'
  path: '>=1.7.0'
  flutter_launcher_icons: '>=0.8.1'

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: '>=0.1.3'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_android: "./assets/mealmatchicon.png"
  image_path_ios: "./assets/mealmatchicon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/logo.png
    - assets/intro-1.png
    - assets/intro-2.png
    - assets/intro-3.png
    - assets/mealmatchicon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
