name: meal_match
description: An interactive social platform to combat food insecurity and improve communities

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+2

environment:
  # https://stackoverflow.com/questions/64621051/how-to-enable-null-safety-in-flutter
  sdk: ">=2.12.0-0 <3.0.0"
  #sdk: '>=2.9.0 <2.10.0'

#https://github.com/danvick/flutter_form_builder/issues/676
#dependency_overrides:
#  intl: ^0.17.0-nullsafety.2
dependency_overrides:
  #firebase_core_platform_interface: "4.0.0-nullsafety.0"
  #firebase_core: "0.8.0-nullsafety.1"
  intl: "0.17.0-nullsafety.2"
  #firebase_core_web: "0.3.0-nullsafety.0"
  http_parser: "4.0.0-nullsafety"

  # These two packages use deprecated APIs that have been removed, so I hand-modified them.
  date_range_picker:
    path: "./date_range_picker-modified-1.0.6"
  flutter_google_places:
    path: "./flutter_google_places-modified-0.2.6"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: "4.0.0-nullsafety.0"
  provider: "5.0.0-nullsafety.3"
  flutter_spinkit: "4.1.2+1"
  gradient_text: "1.0.2"
  dots_indicator: "1.2.0"

  # https://github.com/FirebaseExtended/flutterfire/issues/4959


  # We are not using the Firebase null-safe packages -- they are buggy

  #firebase_core: "0.8.0-nullsafety.1"
  #firebase_analytics: "7.0.1"
  #firebase_auth: "0.21.0-nullsafety.0"
  #firebase_storage: "7.0.0"
  #cloud_firestore: "0.17.0-1.0.nullsafety.0"
  #firebase_messaging: "9.0.0-1.0.nullsafety.0"

  firebase_core: "0.7.0"
  firebase_analytics: "7.0.1"
  firebase_auth: "0.20.0+1"
  firebase_storage: "7.0.0"
  cloud_firestore: "0.16.0"
  firebase_messaging: "8.0.0-dev.14" #use this version because it has major API improvements
  flutter_form_builder: "4.2.0"
  permission_handler: "5.1.0+2"

  # this is a workaround for a recent bug
  # https://github.com/danvick/flutter_form_builder/issues/674
  flutter_typeahead: "<=1.9.1"

  url_launcher: "5.7.10" #"6.0.0-nullsafety.6"; conflict
  google_fonts: "1.1.2"
  dash_chat: "1.1.15"

  shared_preferences: "2.0.0-nullsafety"
  curved_navigation_bar: "0.4.0-nullsafety.0"

  google_maps_webservice: "0.0.19" #"0.0.20-nullsafety.0"; conflict
  uuid: "2.2.2" #"3.0.0-nullsafety.0"; conflict
  geodesy: "0.3.2"
  camera: "0.7.0+2"
  path_provider: "2.0.0-nullsafety"
  # path: "1.7.0" This conflicts!
  flutter_launcher_icons: "0.8.1"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: "1.0.0"

  geolocator: "7.0.0-nullsafety.6"
  geocoding: "1.0.5"


# We are not using testing.
#dev_dependencies:
#  flutter_test:
#    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_android: "./assets/mealmatchicon.png"
  image_path_ios: "./assets/mealmatchicon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/logo.png
    - assets/intro-1.png
    - assets/intro-2.png
    - assets/intro-3.png
    - assets/mealmatchicon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# may not be necessary
analyzer:
  exclude:
    - date_range_picker-modified-1.0.6/**
    - flutter_google_places-modified-0.2.6/**
